version: '3'
services:
  ms:
    image: kastellanos/metasploit-framework:1.0
    volumes:
      - $HOME/.msf4:/home/msf/.msf4
    network_mode: "host"

  db:
    image: postgres:10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data

    network_mode: "host"



volumes:
  pg_data:
    driver: local
